#WAP to input eight numbers from the user and all the unique numbers
s = set()
n1 = input("enter number 1 : ")
s.add(int(n1))
n2 = input("enter number 2 : ")
s.add(int(n2))
n3 = input("enter number 3 : ")
s.add(int(n3))
n4 = input("enter number 4 : ")
s.add(int(n4))
n5 = input("enter number 5 : ")
s.add(int(n5))
n6 = input("enter number 6 : ")
s.add(int(n6))
n7 = input("enter number 7 : ")
s.add(int(n7))
n8 = input("enter number 8 : ")
s.add(int(n8))
print(s)